name: river_reader
description: "A new Flutter project for River Reader."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.0
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.2
  logger: ^2.0.2
  flutter_inappwebview: ^6.0.0 # From task 1.1 in Epic 1[F01]

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
